<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date | custom)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION STATUS    	( UNKNOWN | SKIPPED | UNSUPPORTED | FAILURE | PARTIAL | APPLIED | APPLIED_OTHER )	#IMPLIED>
  <!-- STATUS defaults to APPLIED if BYTES specified and TYPE is non-zero  -->
  <!-- STATUS defaults to APPLIED_OTHER if BYTES specified and TYPE is zero  -->
  <!-- STATUS defaults to UNKNOWN if BYTES are not specified  -->
  <!ATTLIST RELOCATION TYPE     	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION VALUE    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION BYTES    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION SYMBOL_NAME	CDATA	#IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY COMMENT  CDATA  #REQUIRED>

]>
<PROGRAM NAME="additiongo-taskset1" EXE_PATH="/home/kgorna/Documents/tools/pcode-generator/tests/additiongo-taskset1/additiongo-taskset1" EXE_FORMAT="Executable and Linking Format (ELF)" IMAGE_BASE="00200000">
    <INFO_SOURCE USER="kgorna" TOOL="Ghidra 11.0.3" TIMESTAMP="Mon Sep 16 14:25:10 CEST 2024" />
    <PROCESSOR NAME="x86" LANGUAGE_PROVIDER="x86:LE:64:default:golang" ENDIAN="little" />
    <DATATYPES>
        <FUNCTION_DEF NAME="(runtime.gcBlock).findHead" NAMESPACE="/DWARF/gc_blocks.go">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="runtime.gcBlock" DATATYPE_NAMESPACE="/DWARF" SIZE="0x8" />
            <PARAMETER ORDINAL="0x0" DATATYPE="runtime.gcBlock" DATATYPE_NAMESPACE="/DWARF" NAME="b" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="(runtime.gcBlock).markFree" NAMESPACE="/DWARF/gc_blocks.go">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="runtime.gcBlock" DATATYPE_NAMESPACE="/DWARF" SIZE="0x8" />
            <PARAMETER ORDINAL="0x0" DATATYPE="runtime.gcBlock" DATATYPE_NAMESPACE="/DWARF" NAME="b" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="&lt;goroutine_wrapper&gt;" NAMESPACE="/DWARF/scheduler_any.go">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
        </FUNCTION_DEF>
        <TYPE_DEF NAME="Elf64_Addr" NAMESPACE="/DWARF/elf.h" DATATYPE="uint64_t" DATATYPE_NAMESPACE="/DWARF" />
        <STRUCTURE NAME="Elf64_Ehdr" NAMESPACE="/ELF" SIZE="0x40">
            <MEMBER OFFSET="0x0" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="e_ident_magic_num" SIZE="0x1" />
            <MEMBER OFFSET="0x1" DATATYPE="string" DATATYPE_NAMESPACE="/" NAME="e_ident_magic_str" SIZE="0x3" />
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="e_ident_class" SIZE="0x1" />
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="e_ident_data" SIZE="0x1" />
            <MEMBER OFFSET="0x6" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="e_ident_version" SIZE="0x1" />
            <MEMBER OFFSET="0x7" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="e_ident_osabi" SIZE="0x1" />
            <MEMBER OFFSET="0x8" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="e_ident_abiversion" SIZE="0x1" />
            <MEMBER OFFSET="0x9" DATATYPE="byte[7]" DATATYPE_NAMESPACE="/" NAME="e_ident_pad" SIZE="0x7" />
            <MEMBER OFFSET="0x10" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_type" SIZE="0x2" />
            <MEMBER OFFSET="0x12" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_machine" SIZE="0x2" />
            <MEMBER OFFSET="0x14" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="e_version" SIZE="0x4" />
            <MEMBER OFFSET="0x18" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="e_entry" SIZE="0x8" />
            <MEMBER OFFSET="0x20" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="e_phoff" SIZE="0x8" />
            <MEMBER OFFSET="0x28" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="e_shoff" SIZE="0x8" />
            <MEMBER OFFSET="0x30" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="e_flags" SIZE="0x4" />
            <MEMBER OFFSET="0x34" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_ehsize" SIZE="0x2" />
            <MEMBER OFFSET="0x36" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_phentsize" SIZE="0x2" />
            <MEMBER OFFSET="0x38" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_phnum" SIZE="0x2" />
            <MEMBER OFFSET="0x3a" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_shentsize" SIZE="0x2" />
            <MEMBER OFFSET="0x3c" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_shnum" SIZE="0x2" />
            <MEMBER OFFSET="0x3e" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_shstrndx" SIZE="0x2" />
        </STRUCTURE>
        <TYPE_DEF NAME="Elf64_Off" NAMESPACE="/DWARF/elf.h" DATATYPE="uint64_t" DATATYPE_NAMESPACE="/DWARF" />
        <STRUCTURE NAME="Elf64_Phdr" NAMESPACE="/ELF" SIZE="0x38">
            <MEMBER OFFSET="0x0" DATATYPE="Elf_ProgramHeaderType" DATATYPE_NAMESPACE="/ELF" NAME="p_type" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="p_flags" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="p_offset" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="p_vaddr" SIZE="0x8" />
            <MEMBER OFFSET="0x18" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="p_paddr" SIZE="0x8" />
            <MEMBER OFFSET="0x20" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="p_filesz" SIZE="0x8" />
            <MEMBER OFFSET="0x28" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="p_memsz" SIZE="0x8" />
            <MEMBER OFFSET="0x30" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="p_align" SIZE="0x8" />
        </STRUCTURE>
        <STRUCTURE NAME="Elf64_Phdr" NAMESPACE="/DWARF/elf.h" SIZE="0x38">
            <MEMBER OFFSET="0x0" DATATYPE="Elf64_Word" DATATYPE_NAMESPACE="/DWARF/elf.h" NAME="p_type" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="Elf64_Word" DATATYPE_NAMESPACE="/DWARF/elf.h" NAME="p_flags" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="Elf64_Off" DATATYPE_NAMESPACE="/DWARF/elf.h" NAME="p_offset" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="Elf64_Addr" DATATYPE_NAMESPACE="/DWARF/elf.h" NAME="p_vaddr" SIZE="0x8" />
            <MEMBER OFFSET="0x18" DATATYPE="Elf64_Addr" DATATYPE_NAMESPACE="/DWARF/elf.h" NAME="p_paddr" SIZE="0x8" />
            <MEMBER OFFSET="0x20" DATATYPE="Elf64_Xword" DATATYPE_NAMESPACE="/DWARF/elf.h" NAME="p_filesz" SIZE="0x8" />
            <MEMBER OFFSET="0x28" DATATYPE="Elf64_Xword" DATATYPE_NAMESPACE="/DWARF/elf.h" NAME="p_memsz" SIZE="0x8" />
            <MEMBER OFFSET="0x30" DATATYPE="Elf64_Xword" DATATYPE_NAMESPACE="/DWARF/elf.h" NAME="p_align" SIZE="0x8" />
        </STRUCTURE>
        <STRUCTURE NAME="Elf64_Shdr" NAMESPACE="/ELF" SIZE="0x40">
            <MEMBER OFFSET="0x0" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_name" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="Elf_SectionHeaderType" DATATYPE_NAMESPACE="/ELF" NAME="sh_type" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="sh_flags" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="sh_addr" SIZE="0x8" />
            <MEMBER OFFSET="0x18" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="sh_offset" SIZE="0x8" />
            <MEMBER OFFSET="0x20" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="sh_size" SIZE="0x8" />
            <MEMBER OFFSET="0x28" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_link" SIZE="0x4" />
            <MEMBER OFFSET="0x2c" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_info" SIZE="0x4" />
            <MEMBER OFFSET="0x30" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="sh_addralign" SIZE="0x8" />
            <MEMBER OFFSET="0x38" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="sh_entsize" SIZE="0x8" />
        </STRUCTURE>
        <STRUCTURE NAME="Elf64_Sym" NAMESPACE="/ELF" SIZE="0x18">
            <MEMBER OFFSET="0x0" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="st_name" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="st_info" SIZE="0x1" />
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="st_other" SIZE="0x1" />
            <MEMBER OFFSET="0x6" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="st_shndx" SIZE="0x2" />
            <MEMBER OFFSET="0x8" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="st_value" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="st_size" SIZE="0x8" />
        </STRUCTURE>
        <TYPE_DEF NAME="Elf64_Word" NAMESPACE="/DWARF/elf.h" DATATYPE="uint32_t" DATATYPE_NAMESPACE="/DWARF" />
        <TYPE_DEF NAME="Elf64_Xword" NAMESPACE="/DWARF/elf.h" DATATYPE="uint64_t" DATATYPE_NAMESPACE="/DWARF" />
        <ENUM NAME="Elf_ProgramHeaderType" NAMESPACE="/ELF" SIZE="0x4">
            <ENUM_ENTRY NAME="PT_NULL" VALUE="0x0" COMMENT="" />
            <ENUM_ENTRY NAME="PT_LOAD" VALUE="0x1" COMMENT="" />
            <ENUM_ENTRY NAME="PT_DYNAMIC" VALUE="0x2" COMMENT="" />
            <ENUM_ENTRY NAME="PT_INTERP" VALUE="0x3" COMMENT="" />
            <ENUM_ENTRY NAME="PT_NOTE" VALUE="0x4" COMMENT="" />
            <ENUM_ENTRY NAME="PT_SHLIB" VALUE="0x5" COMMENT="" />
            <ENUM_ENTRY NAME="PT_PHDR" VALUE="0x6" COMMENT="" />
            <ENUM_ENTRY NAME="PT_TLS" VALUE="0x7" COMMENT="" />
            <ENUM_ENTRY NAME="PT_GNU_EH_FRAME" VALUE="0x6474e550" COMMENT="" />
            <ENUM_ENTRY NAME="PT_GNU_STACK" VALUE="0x6474e551" COMMENT="" />
            <ENUM_ENTRY NAME="PT_GNU_RELRO" VALUE="0x6474e552" COMMENT="" />
        </ENUM>
        <ENUM NAME="Elf_SectionHeaderType" NAMESPACE="/ELF" SIZE="0x4">
            <ENUM_ENTRY NAME="SHT_NULL" VALUE="0x0" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_PROGBITS" VALUE="0x1" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_SYMTAB" VALUE="0x2" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_STRTAB" VALUE="0x3" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_RELA" VALUE="0x4" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_HASH" VALUE="0x5" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_DYNAMIC" VALUE="0x6" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_NOTE" VALUE="0x7" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_NOBITS" VALUE="0x8" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_REL" VALUE="0x9" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_SHLIB" VALUE="0xa" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_DYNSYM" VALUE="0xb" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_INIT_ARRAY" VALUE="0xe" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_FINI_ARRAY" VALUE="0xf" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_PREINIT_ARRAY" VALUE="0x10" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_GROUP" VALUE="0x11" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_SYMTAB_SHNDX" VALUE="0x12" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_ANDROID_REL" VALUE="0x60000001" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_ANDROID_RELA" VALUE="0x60000002" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_GNU_ATTRIBUTES" VALUE="0x6ffffff5" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_GNU_HASH" VALUE="0x6ffffff6" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_GNU_LIBLIST" VALUE="0x6ffffff7" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_CHECKSUM" VALUE="0x6ffffff8" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_SUNW_move" VALUE="0x6ffffffa" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_SUNW_COMDAT" VALUE="0x6ffffffb" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_SUNW_syminfo" VALUE="0x6ffffffc" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_GNU_verdef" VALUE="0x6ffffffd" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_GNU_verneed" VALUE="0x6ffffffe" COMMENT="" />
            <ENUM_ENTRY NAME="SHT_GNU_versym" VALUE="0x6fffffff" COMMENT="" />
        </ENUM>
        <TYPE_DEF NAME="Phdr" NAMESPACE="/DWARF/__init_tls.c" DATATYPE="Elf64_Phdr" DATATYPE_NAMESPACE="/DWARF/elf.h" />
        <STRUCTURE NAME="[]internal/cpu.option" NAMESPACE="/DWARF/_UNCATEGORIZED_" SIZE="0x18">
            <MEMBER OFFSET="0x0" DATATYPE="internal/cpu.option *" DATATYPE_NAMESPACE="/DWARF/_UNCATEGORIZED_" NAME="ptr" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="uintptr" DATATYPE_NAMESPACE="/DWARF" NAME="len" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="uintptr" DATATYPE_NAMESPACE="/DWARF" NAME="cap" SIZE="0x8" />
        </STRUCTURE>
        <STRUCTURE NAME="[]string" NAMESPACE="/DWARF/_UNCATEGORIZED_" SIZE="0x18">
            <MEMBER OFFSET="0x0" DATATYPE="string *" DATATYPE_NAMESPACE="/DWARF/_UNCATEGORIZED_" NAME="ptr" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="uintptr" DATATYPE_NAMESPACE="/DWARF" NAME="len" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="uintptr" DATATYPE_NAMESPACE="/DWARF" NAME="cap" SIZE="0x8" />
        </STRUCTURE>
        <FUNCTION_DEF NAME="_Exit" NAMESPACE="/DWARF/_Exit.c">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
            <PARAMETER ORDINAL="0x0" DATATYPE="int" DATATYPE_NAMESPACE="/DWARF" NAME="ec" SIZE="0x4" />
        </FUNCTION_DEF>
        <TYPE_DEF NAME="__ARRAY_SIZE_TYPE__" NAMESPACE="/DWARF" DATATYPE="uint" DATATYPE_NAMESPACE="/" />
        <FUNCTION_DEF NAME="__block_all_sigs" NAMESPACE="/DWARF/block.c">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
            <PARAMETER ORDINAL="0x0" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="set" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__block_app_sigs" NAMESPACE="/DWARF/block.c">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
            <PARAMETER ORDINAL="0x0" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="set" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__copy_tls" NAMESPACE="/DWARF/__init_tls.c">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void *" DATATYPE_NAMESPACE="/" SIZE="0x8" />
            <PARAMETER ORDINAL="0x0" DATATYPE="uchar *" DATATYPE_NAMESPACE="/" NAME="mem" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__errno_location" NAMESPACE="/DWARF/__errno_location.c">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="int *" DATATYPE_NAMESPACE="/DWARF" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__init_libc" NAMESPACE="/DWARF/__libc_start_main.c">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
            <PARAMETER ORDINAL="0x0" DATATYPE="char * *" DATATYPE_NAMESPACE="/" NAME="envp" SIZE="0x8" />
            <PARAMETER ORDINAL="0x1" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="pn" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__init_tp" NAMESPACE="/DWARF/__init_tls.c">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="int" DATATYPE_NAMESPACE="/DWARF" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="p" SIZE="0x8" />
        </FUNCTION_DEF>
        <STRUCTURE NAME="__libc" NAMESPACE="/DWARF/libc.h" SIZE="0x68">
            <MEMBER OFFSET="0x0" DATATYPE="char" DATATYPE_NAMESPACE="/" NAME="can_do_threads" SIZE="0x1" />
            <MEMBER OFFSET="0x1" DATATYPE="char" DATATYPE_NAMESPACE="/" NAME="threaded" SIZE="0x1" />
            <MEMBER OFFSET="0x2" DATATYPE="char" DATATYPE_NAMESPACE="/" NAME="secure" SIZE="0x1" />
            <MEMBER OFFSET="0x3" DATATYPE="char" DATATYPE_NAMESPACE="/" NAME="need_locks" SIZE="0x1" />
            <MEMBER OFFSET="0x4" DATATYPE="int" DATATYPE_NAMESPACE="/DWARF" NAME="threads_minus_1" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="size_t *" DATATYPE_NAMESPACE="/DWARF" NAME="auxv" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="tls_module *" DATATYPE_NAMESPACE="/DWARF/libc.h" NAME="tls_head" SIZE="0x8" />
            <MEMBER OFFSET="0x18" DATATYPE="size_t" DATATYPE_NAMESPACE="/DWARF" NAME="tls_size" SIZE="0x8" />
            <MEMBER OFFSET="0x20" DATATYPE="size_t" DATATYPE_NAMESPACE="/DWARF" NAME="tls_align" SIZE="0x8" />
            <MEMBER OFFSET="0x28" DATATYPE="size_t" DATATYPE_NAMESPACE="/DWARF" NAME="tls_cnt" SIZE="0x8" />